In [1]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [3]:
data = pd.read_csv('car.data')
print(data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [33]:
x = data[['buying', 'maint', 'safety']].values
y = data[['class']]

In [34]:
print(x, y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


In [35]:
# converting the X to numbers
Le = LabelEncoder()
for i in range(len(x[0])):
    x[:, i] = Le.fit_transform(x[:, i])
    
print(x)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [37]:
print(y.shape)

(1728, 1)


In [38]:
# converting the Y to numbers
label_maping = {'unacc':0, 'acc':1, 'good':2, 'vgood':3}
y['class'] = y['class'].map(label_maping)
y = np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


<ipython-input-38-f7e3c7763abf>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class'] = y['class'].map(label_maping)


In [39]:
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')

In [41]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [43]:
knn.fit(x_train,y_train)

<ipython-input-43-17b0ab828d68>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train,y_train)


KNeighborsClassifier(n_neighbors=25)

In [44]:
prediction = knn.predict(x_test)
accuracy = metrics.accuracy_score(y_test,prediction)

In [47]:
tmp = []
for key, value in label_maping.items():
    aKey = key
    aValue = value
    tmp.append(aKey)

print(tmp)

['unacc', 'acc', 'good', 'vgood']


In [48]:
print(prediction.shape)

(346,)


In [52]:
print(y_test.shape)

(346, 1)


In [63]:
for i in range(int(prediction.shape[0])):
    print(tmp[int(y_test[i])] + "   >>>>   " + tmp[prediction[i]])

unacc   >>>>   unacc
unacc   >>>>   unacc
acc   >>>>   acc
unacc   >>>>   unacc
acc   >>>>   acc
unacc   >>>>   unacc
unacc   >>>>   acc
unacc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
acc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
acc   >>>>   unacc
acc   >>>>   good
unacc   >>>>   unacc
unacc   >>>>   acc
acc   >>>>   unacc
unacc   >>>>   vgood
vgood   >>>>   unacc
acc   >>>>   acc
unacc   >>>>   unacc
unacc   >>>>   unacc
acc   >>>>   vgood
unacc   >>>>   acc
unacc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
acc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
acc   >>>>   acc
acc   >>>>   unacc
unacc   >>>>   unacc
acc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   unacc
unacc   >>>>   acc
unacc   >>>>   unacc
unacc   >>>>

In [62]:
print(accuracy)

0.7283236994219653


In [65]:
print("actual value: ", y[20])
print("Predicted value: ",knn.predict(x)[20])

actual value:  [0]
Predicted value:  0
